#ddev-generated
services:
  web:
    volumes:
      - type: volume
        source: opencode
        target: /mnt/opencode
    environment:
      XDG_CONFIG_HOME: /mnt/opencode/config
      XDG_DATA_HOME: /mnt/opencode/data
      XDG_STATE_HOME: /mnt/opencode/state
      OPENCODE_CONFIG: /mnt/opencode/config/opencode/opencode.json

volumes:
  opencode: {}
